baseURL = "https://pokepoint.ru/"

copyright = "ПокеПоинт"
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "Europe/Moscow"
timeout = "120s"
title = "content/logo.jpg"

[params]
  defaultTheme = "light"
  description = "Авторские права на буквальную и графическую информацию, представленную на этом веб-сайте о Pokémon TCG, включая изображения карт и текст, принадлежат компании Pokémon Company, Nintendo, Game Freak и/или Creatures. Этот веб-сайт не создан, не одобрен, не поддерживается и не связан с Pokémon, Nintendo, Game Freak или Creatures. Вся опубликованная информация носит рекомендательный характер, не является торговым предложением."
  title = "Каталог рекомендованных цен"
  [params.author]
    email = "user@example.com"
    name = "Your Name"
  [params.socialIcons]
    #facebook = "https://www.facebook.com/"
    #instagram = "https://www.instagram.com/"
    #github = "https://github.com/nicokaiser/hugo-theme-gallery/"
    #youtube = "https://www.youtube.com/"
    email = "user@example.com"
    #website = "https://example.com"
    telegram = "https://example.com"
    #pixelfed = "https://example.com"
    #mixcloud = "https://example.com"
    #flickr = "https://www.flickr.com"
    #500px = "https://500px"
    #whatsapp = "1234567890"
  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  vendorDir = "_vendor"
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

#[menu]
#  [[menu.footer]]
#    name = "GitHub"
#    url = "https://github.com/nicokaiser/hugo-theme-gallery/"
#    weight = 3

#[services]
#  [services.rss]
#    limit = 100
